.TH "C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/board.cpp" 3 "Mon Feb 25 2019" "4Gewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/board.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'board\&.h'\fP
.br
\fC#include 'shaderdebugger\&.h'\fP
.br
\fC#include 'gldisc\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 4Gewinnt from the source code\&.
