.TH "C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/glbody.h" 3 "Mon Feb 25 2019" "4Gewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/glbody.h
.SH SYNOPSIS
.br
.PP
\fC#include <QVector>\fP
.br
\fC#include <QOpenGLTexture>\fP
.br
\fC#include <QOpenGLFunctions>\fP
.br
\fC#include 'glesrenderer\&.h'\fP
.br
\fC#include 'glpoint\&.h'\fP
.br
\fC#include 'gldefines\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGLBody\fP"
.br
.RI "A 3D body that uses a \fBGLESRenderer\fP for drawing and \fBGLPoint\fP objects for defining its surface\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 4Gewinnt from the source code\&.
