.TH "C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/glbody.cpp" 3 "Mon Feb 25 2019" "4Gewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/glbody.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'glbody\&.h'\fP
.br
\fC#include <QImage>\fP
.br
\fC#include <QtOpenGL/QGLWidget>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <math\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 4Gewinnt from the source code\&.
