.TH "C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/glcolorrgba.h" 3 "Mon Feb 25 2019" "4Gewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/glcolorrgba.h
.SH SYNOPSIS
.br
.PP
\fC#include <QVector4D>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGLColorRgba\fP"
.br
.RI "The GlColorRgba class is a convenience class to replace QVector4D for color variables\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 4Gewinnt from the source code\&.
