.TH "GLColorRgba" 3 "Mon Feb 25 2019" "4Gewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLColorRgba \- The GlColorRgba class is a convenience class to replace QVector4D for color variables\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glcolorrgba\&.h>\fP
.PP
Inherits QVector4D\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGLColorRgba\fP (float r=0\&.0, float g=0\&.0, float b=0\&.0, float a=1\&.0)"
.br
.ti -1c
.RI "\fBGLColorRgba\fP (const \fBGLColorRgba\fP &other)"
.br
.ti -1c
.RI "\fBGLColorRgba\fP (const QVector4D &other)"
.br
.ti -1c
.RI "\fBGLColorRgba\fP \fBinverted\fP ()"
.br
.ti -1c
.RI "\fBGLColorRgba\fP \fBoperator *\fP (float factor)"
.br
.ti -1c
.RI "float \fBred\fP () const"
.br
.ti -1c
.RI "float \fBgreen\fP () const"
.br
.ti -1c
.RI "float \fBblue\fP () const"
.br
.ti -1c
.RI "float \fBalpha\fP () const"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBGLColorRgba\fP \fBclBlack\fP = \fBGLColorRgba\fP(0\&.0,0\&.0,0\&.0,1\&.0)"
.br
.ti -1c
.RI "static \fBGLColorRgba\fP \fBclRed\fP = \fBGLColorRgba\fP(1\&.0,0\&.0,0\&.0,1\&.0)"
.br
.ti -1c
.RI "static \fBGLColorRgba\fP \fBclYellow\fP = \fBGLColorRgba\fP(1\&.0,1\&.0,0\&.0,1\&.0)"
.br
.ti -1c
.RI "static \fBGLColorRgba\fP \fBclGreen\fP = \fBGLColorRgba\fP(0\&.0,1\&.0,0\&.0,1\&.0)"
.br
.ti -1c
.RI "static \fBGLColorRgba\fP \fBclCyan\fP = \fBGLColorRgba\fP(0\&.0,1\&.0,1\&.0,1\&.0)"
.br
.ti -1c
.RI "static \fBGLColorRgba\fP \fBclBlue\fP = \fBGLColorRgba\fP(0\&.0,0\&.0,1\&.0,1\&.0)"
.br
.ti -1c
.RI "static \fBGLColorRgba\fP \fBclMagenta\fP = \fBGLColorRgba\fP(1\&.0,0\&.0,1\&.0,1\&.0)"
.br
.ti -1c
.RI "static \fBGLColorRgba\fP \fBclGray\fP = \fBGLColorRgba\fP(0\&.5,0\&.5,0\&.5,1\&.0)"
.br
.ti -1c
.RI "static \fBGLColorRgba\fP \fBclWhite\fP = \fBGLColorRgba\fP(1\&.0,1\&.0,1\&.0,1\&.0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The GlColorRgba class is a convenience class to replace QVector4D for color variables\&. 
.PP
Definition at line 9 of file glcolorrgba\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GLColorRgba::GLColorRgba (float r = \fC0\&.0\fP, float g = \fC0\&.0\fP, float b = \fC0\&.0\fP, float a = \fC1\&.0\fP)"

.PP
Definition at line 13 of file glcolorrgba\&.cpp\&.
.SS "GLColorRgba::GLColorRgba (const \fBGLColorRgba\fP & other)"

.PP
Definition at line 19 of file glcolorrgba\&.cpp\&.
.SS "GLColorRgba::GLColorRgba (const QVector4D & other)"

.PP
Definition at line 24 of file glcolorrgba\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "float GLColorRgba::alpha () const\fC [inline]\fP"

.PP
Definition at line 24 of file glcolorrgba\&.h\&.
.SS "float GLColorRgba::blue () const\fC [inline]\fP"

.PP
Definition at line 23 of file glcolorrgba\&.h\&.
.SS "float GLColorRgba::green () const\fC [inline]\fP"

.PP
Definition at line 22 of file glcolorrgba\&.h\&.
.SS "\fBGLColorRgba\fP GLColorRgba::inverted ()"
Returns the inverted color with a= 1\&.0 
.PP
Definition at line 32 of file glcolorrgba\&.cpp\&.
.SS "\fBGLColorRgba\fP GLColorRgba::operator * (float factor)"

.PP
Definition at line 37 of file glcolorrgba\&.cpp\&.
.SS "float GLColorRgba::red () const\fC [inline]\fP"

.PP
Definition at line 21 of file glcolorrgba\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGLColorRgba\fP GLColorRgba::clBlack = \fBGLColorRgba\fP(0\&.0,0\&.0,0\&.0,1\&.0)\fC [static]\fP"

.PP
Definition at line 27 of file glcolorrgba\&.h\&.
.SS "\fBGLColorRgba\fP GLColorRgba::clBlue = \fBGLColorRgba\fP(0\&.0,0\&.0,1\&.0,1\&.0)\fC [static]\fP"

.PP
Definition at line 32 of file glcolorrgba\&.h\&.
.SS "\fBGLColorRgba\fP GLColorRgba::clCyan = \fBGLColorRgba\fP(0\&.0,1\&.0,1\&.0,1\&.0)\fC [static]\fP"

.PP
Definition at line 31 of file glcolorrgba\&.h\&.
.SS "\fBGLColorRgba\fP GLColorRgba::clGray = \fBGLColorRgba\fP(0\&.5,0\&.5,0\&.5,1\&.0)\fC [static]\fP"

.PP
Definition at line 34 of file glcolorrgba\&.h\&.
.SS "\fBGLColorRgba\fP GLColorRgba::clGreen = \fBGLColorRgba\fP(0\&.0,1\&.0,0\&.0,1\&.0)\fC [static]\fP"

.PP
Definition at line 30 of file glcolorrgba\&.h\&.
.SS "\fBGLColorRgba\fP GLColorRgba::clMagenta = \fBGLColorRgba\fP(1\&.0,0\&.0,1\&.0,1\&.0)\fC [static]\fP"

.PP
Definition at line 33 of file glcolorrgba\&.h\&.
.SS "\fBGLColorRgba\fP GLColorRgba::clRed = \fBGLColorRgba\fP(1\&.0,0\&.0,0\&.0,1\&.0)\fC [static]\fP"

.PP
Definition at line 28 of file glcolorrgba\&.h\&.
.SS "\fBGLColorRgba\fP GLColorRgba::clWhite = \fBGLColorRgba\fP(1\&.0,1\&.0,1\&.0,1\&.0)\fC [static]\fP"

.PP
Definition at line 35 of file glcolorrgba\&.h\&.
.SS "\fBGLColorRgba\fP GLColorRgba::clYellow = \fBGLColorRgba\fP(1\&.0,1\&.0,0\&.0,1\&.0)\fC [static]\fP"

.PP
Definition at line 29 of file glcolorrgba\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 4Gewinnt from the source code\&.
