.TH "C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/gldefines.h" 3 "Mon Feb 25 2019" "4Gewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/gldefines.h \- Convenience objects for building OpenGL surfaces\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QVector3D>\fP
.br
\fC#include 'glcolorrgba\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIndexType\fP   GLushort"
.br
.in -1c
.SH "Detailed Description"
.PP 
Convenience objects for building OpenGL surfaces\&. 

Predefined 3D-vectors and colors that are frequently used\&. 
.PP
Definition in file \fBgldefines\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define IndexType   GLushort"

.PP
Definition at line 22 of file gldefines\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 4Gewinnt from the source code\&.
