.TH "C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/glesrenderer.h" 3 "Mon Feb 25 2019" "4Gewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/glesrenderer.h
.SH SYNOPSIS
.br
.PP
\fC#include <QOpenGLShaderProgram>\fP
.br
\fC#include <QOpenGLFunctions>\fP
.br
\fC#include <QList>\fP
.br
\fC#include <QStack>\fP
.br
\fC#include 'glcolorrgba\&.h'\fP
.br
\fC#include 'gldefines\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGLESRenderer\fP"
.br
.RI "A render program that can be used as a simple replacement for the OpenGL fixed function pipeline\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 4Gewinnt from the source code\&.
