.TH "C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/glpoint.h" 3 "Mon Feb 25 2019" "4Gewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/glpoint.h
.SH SYNOPSIS
.br
.PP
\fC#include <QVector3D>\fP
.br
\fC#include <QMatrix3x3>\fP
.br
\fC#include <QMatrix4x4>\fP
.br
\fC#include 'glcolorrgba\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGLPoint\fP"
.br
.RI "The \fBGLPoint\fP class A Point containing data for a surface point\&. This class is used in binary read and write functions\&. DO NOT add virtual methods, DO NOT change order of declarations\&. xxxPointer methods return the addresses needed by OpenGL attribute functions\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 4Gewinnt from the source code\&.
