.TH "C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/main.cpp" 3 "Mon Feb 25 2019" "4Gewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QGuiApplication>\fP
.br
\fC#include <QQmlApplicationEngine>\fP
.br
\fC#include <QTranslator>\fP
.br
\fC#include 'myglitem\&.h'\fP
.br
\fC#include <QQmlContext>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 8 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 4Gewinnt from the source code\&.
