.TH "C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/myglitem.cpp" 3 "Mon Feb 25 2019" "4Gewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/myglitem.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'myglitem\&.h'\fP
.br
\fC#include 'glitem\&.h'\fP
.br
\fC#include 'glpoint\&.h'\fP
.br
\fC#include <QVector3D>\fP
.br
\fC#include <QPropertyAnimation>\fP
.br
\fC#include <QQuickWindow>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 4Gewinnt from the source code\&.
