.TH "C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/myglitem.h" 3 "Mon Feb 25 2019" "4Gewinnt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/svwei/Documents/workspace_qt/4gewinnt/src/myglitem.h
.SH SYNOPSIS
.br
.PP
\fC#include 'glitem\&.h'\fP
.br
\fC#include 'gldisc\&.h'\fP
.br
\fC#include <QOpenGLBuffer>\fP
.br
\fC#include 'board\&.h'\fP
.br
\fC#include <QTimer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyGlItem\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 4Gewinnt from the source code\&.
